# Generated by Django 5.1.15 on 2026-03-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("structure", "0001_initial"),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="factindicadorcampanha",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.campaign",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="factrespostapergunta",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveys.campaign"
            ),
        ),
        migrations.AddField(
            model_name="factrespostapergunta",
            name="dim_estrutura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.dimestrutura"
            ),
        ),
        migrations.AddField(
            model_name="factscoredimensao",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveys.campaign"
            ),
        ),
        migrations.AddField(
            model_name="factscoredimensao",
            name="dim_dimensao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.dimdimensaohse",
            ),
        ),
        migrations.AddField(
            model_name="factscoredimensao",
            name="dim_estrutura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.dimestrutura"
            ),
        ),
        migrations.AddField(
            model_name="factscoredimensao",
            name="dim_tempo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.dimtempo",
            ),
        ),
        migrations.AddField(
            model_name="sectoranalysis",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveys.campaign"
            ),
        ),
        migrations.AddField(
            model_name="sectoranalysis",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="structure.setor"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dimestrutura",
            unique_together={("unidade", "setor")},
        ),
        migrations.AlterUniqueTogether(
            name="factrespostapergunta",
            unique_together={("campaign", "dim_estrutura", "pergunta_numero")},
        ),
        migrations.AddIndex(
            model_name="factscoredimensao",
            index=models.Index(
                fields=["campaign", "nivel_risco"],
                name="analytics_f_campaig_e81a6a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="factscoredimensao",
            unique_together={("campaign", "dim_estrutura", "dim_dimensao")},
        ),
    ]
