# Generated by Django 5.1.15 on 2026-03-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faixa_etaria", models.CharField(blank=True, max_length=50)),
                ("tempo_empresa", models.CharField(blank=True, max_length=50)),
                ("genero", models.CharField(blank=True, max_length=50)),
                ("respostas", models.JSONField(default=dict)),
                ("comentario_livre", models.TextField(blank=True)),
                ("sentimento_score", models.FloatField(blank=True, null=True)),
                ("sentimento_categorias", models.JSONField(blank=True, null=True)),
                ("lgpd_aceito", models.BooleanField(default=True)),
                ("lgpd_aceito_em", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Resposta de Pesquisa",
                "verbose_name_plural": "Respostas de Pesquisa",
            },
        ),
    ]
