# Generated by Django 5.1.15 on 2026-03-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("responses", "0001_initial"),
        ("structure", "0001_initial"),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas",
                to="surveys.campaign",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="structure.setor"
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="unidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="structure.unidade"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["campaign", "created_at"], name="responses_s_campaig_ed3d22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["campaign", "unidade"], name="responses_s_campaig_6b5c09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["campaign", "setor"], name="responses_s_campaig_9854c5_idx"
            ),
        ),
    ]
