# Generated by Django 5.1.15 on 2026-03-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invitations", "0001_initial"),
        ("structure", "0001_initial"),
        ("surveys", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyinvitation",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="surveys.campaign",
            ),
        ),
        migrations.AddField(
            model_name="surveyinvitation",
            name="cargo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="structure.cargo",
            ),
        ),
        migrations.AddField(
            model_name="surveyinvitation",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="tenants.empresa",
            ),
        ),
        migrations.AddField(
            model_name="surveyinvitation",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="structure.setor"
            ),
        ),
        migrations.AddField(
            model_name="surveyinvitation",
            name="unidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="structure.unidade"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyinvitation",
            index=models.Index(
                fields=["campaign", "status"], name="invitations_campaig_3a4118_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyinvitation",
            index=models.Index(
                fields=["hash_token"], name="invitations_hash_to_bca542_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyinvitation",
            index=models.Index(
                fields=["expires_at"], name="invitations_expires_b9431c_idx"
            ),
        ),
    ]
