"""
This migration was auto-generated by Django when it detected that the
AuditLog model's Meta.indexes had no explicit names (auto-naming) while
0001_initial.py used explicit names.

Root cause: 0001_initial.py was extended with CreateModel('AuditLog') and
AddIndex operations AFTER it had already been applied in some environments.
This migration handles all upgrade paths:

  A) accounts_auditlog table is completely absent (0001 was applied before
     AuditLog was ever added to it)  → create table + indexes.
  B) Table exists but empresa_id column is missing (0001 was applied before
     the empresa FK was added)       → add column + create missing indexes.
  C) Table exists with all columns but named indexes are missing            → create the three named indexes only.
  D) Table exists with everything already in place                          → no-op.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- ----------------------------------------------------------------
                -- Case A: table does not exist at all → create it from scratch
                -- ----------------------------------------------------------------
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.tables
                    WHERE table_schema = current_schema()
                      AND table_name   = 'accounts_auditlog'
                ) THEN
                    CREATE TABLE accounts_auditlog (
                        id          BIGSERIAL    PRIMARY KEY,
                        acao        VARCHAR(50)  NOT NULL,
                        descricao   TEXT         NOT NULL,
                        ip          INET,
                        user_agent  VARCHAR(500) NOT NULL DEFAULT '',
                        created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
                        empresa_id  BIGINT       REFERENCES tenants_empresa(id)
                                                 ON DELETE SET NULL,
                        user_id     INTEGER      REFERENCES auth_user(id)
                                                 ON DELETE SET NULL
                    );
                    CREATE INDEX accounts_au_user_id_idx
                        ON accounts_auditlog (user_id,    created_at);
                    CREATE INDEX accounts_au_empresa_idx
                        ON accounts_auditlog (empresa_id, created_at);
                    CREATE INDEX accounts_au_acao_idx
                        ON accounts_auditlog (acao,       created_at);

                ELSE
                    -- ------------------------------------------------------------
                    -- Case B: table exists but empresa_id column is missing
                    -- ------------------------------------------------------------
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = current_schema()
                          AND table_name   = 'accounts_auditlog'
                          AND column_name  = 'empresa_id'
                    ) THEN
                        ALTER TABLE accounts_auditlog
                            ADD COLUMN empresa_id BIGINT
                                REFERENCES tenants_empresa(id) ON DELETE SET NULL;
                    END IF;

                    -- ------------------------------------------------------------
                    -- Case C / D: ensure all three named indexes exist
                    -- ------------------------------------------------------------
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = current_schema()
                          AND indexname  = 'accounts_au_user_id_idx'
                    ) THEN
                        CREATE INDEX accounts_au_user_id_idx
                            ON accounts_auditlog (user_id, created_at);
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = current_schema()
                          AND indexname  = 'accounts_au_empresa_idx'
                    ) THEN
                        CREATE INDEX accounts_au_empresa_idx
                            ON accounts_auditlog (empresa_id, created_at);
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE schemaname = current_schema()
                          AND indexname  = 'accounts_au_acao_idx'
                    ) THEN
                        CREATE INDEX accounts_au_acao_idx
                            ON accounts_auditlog (acao, created_at);
                    END IF;
                END IF;
            END
            $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
