"""
This migration was auto-generated by Django when it detected that the
AuditLog model's Meta.indexes had no explicit names (auto-naming) while
0001_initial.py used explicit names.

Root cause: 0001_initial.py was extended with AddIndex operations AFTER it had
already been applied in some environments, so those environments have the
AuditLog table but are missing the three explicit indexes.

This migration ensures all three indexes exist, creating them if absent,
so that future migrations can safely reference them by name.
The state is left unchanged (explicit names from 0001 are kept).
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- user + created_at index
                IF NOT EXISTS (
                    SELECT 1 FROM pg_indexes
                    WHERE schemaname = current_schema()
                      AND indexname = 'accounts_au_user_id_idx'
                ) THEN
                    CREATE INDEX accounts_au_user_id_idx
                        ON accounts_auditlog (user_id, created_at);
                END IF;

                -- empresa + created_at index
                IF NOT EXISTS (
                    SELECT 1 FROM pg_indexes
                    WHERE schemaname = current_schema()
                      AND indexname = 'accounts_au_empresa_idx'
                ) THEN
                    CREATE INDEX accounts_au_empresa_idx
                        ON accounts_auditlog (empresa_id, created_at);
                END IF;

                -- acao + created_at index
                IF NOT EXISTS (
                    SELECT 1 FROM pg_indexes
                    WHERE schemaname = current_schema()
                      AND indexname = 'accounts_au_acao_idx'
                ) THEN
                    CREATE INDEX accounts_au_acao_idx
                        ON accounts_auditlog (acao, created_at);
                END IF;
            END
            $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
