# Generated by Django 5.1.15 on 2026-03-15 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actions", "0001_initial"),
        ("surveys", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistnr1etapa",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_etapas",
                to="surveys.campaign",
            ),
        ),
        migrations.AddField(
            model_name="checklistnr1etapa",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.empresa"
            ),
        ),
        migrations.AddField(
            model_name="checklistnr1item",
            name="etapa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="actions.checklistnr1etapa",
            ),
        ),
        migrations.AddField(
            model_name="evidencianr1",
            name="checklist_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidencias",
                to="actions.checklistnr1item",
            ),
        ),
        migrations.AddField(
            model_name="evidencianr1",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.empresa"
            ),
        ),
        migrations.AddField(
            model_name="evidencianr1",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planoacao",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planos_acao",
                to="surveys.campaign",
            ),
        ),
        migrations.AddField(
            model_name="planoacao",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planos_criados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planoacao",
            name="dimensao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="surveys.dimensao",
            ),
        ),
        migrations.AddField(
            model_name="planoacao",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planos_acao",
                to="tenants.empresa",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checklistnr1etapa",
            unique_together={("campaign", "numero_etapa")},
        ),
    ]
